### PR TITLE
Less false positives

### PR DESCRIPTION
**Pull request by do3cc**
This is a fix for https://github.com/gforcada/flake8-plone-api/issues/3

### CODE REVIEW

**Comment by gforcada** [comment]
Thanks!

Would you mind adding a test? They are really easy to write. See https://github.com/gforcada/flake8-plone-api/blob/master/run_tests.py

**Comment by do3cc** [comment]
I've added a test.
I am confused about the check code now, I will write some questions in the file

**Comment by do3cc** [comment]
What about a new release with this change? currently we have lots of failing tests in our infrastructure because of this.

**Comment by gforcada** [comment]
Yes, sorry, it fell through the cracks... will do right away after the plone hotfix :-)

**Comment by gforcada** [comment]
Released! https://pypi.python.org/pypi/flake8-plone-api

**Comment by do3cc** [comment]
thank you!

**Pull request merged**
